name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push with commit id
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: markday1962/python-app:${{ env.sha_short }}
      -
        name: Build and push with latst tag
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: markday1962/python-app:latest
